### ISSUE TITLE
The voice connection is not established in 15 seconds

### ISSUE THREAD

**Issue by LucasB25** [shipgirlproject/Shoukaku#197]
```
[27/08/2024] [17:05:30] [antiCrash.js] [Lavamusic] » ✖  error     Unhandled Rejection at: Promise {
  <rejected> Error: The voice connection is not established in 15 seconds
      at Connection.connect (file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/node_modules/shoukaku/dist/index.mjs:364:15)
      at async ShoukakuClient.joinVoiceChannel (file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/node_modules/shoukaku/dist/index.mjs:1325:7)
      at async Queue.create (file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/dist/structures/Queue.js:35:22)
      at async file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/dist/events/player/NodeConnect.js:21:17
      at async Promise.all (index 1)
      at async NodeConnect.run (file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/dist/events/player/NodeConnect.js:16:9)
} reason: Error: The voice connection is not established in 15 seconds
    at Connection.connect (file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/node_modules/shoukaku/dist/index.mjs:364:15)
    at async ShoukakuClient.joinVoiceChannel (file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/node_modules/shoukaku/dist/index.mjs:1325:7)
    at async Queue.create (file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/dist/structures/Queue.js:35:22)
    at async file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/dist/events/player/NodeConnect.js:21:17
    at async Promise.all (index 1)
    at async NodeConnect.run (file:///C:/Users/LucasB25/Documents/GitHub/Panaisdev/dist/events/player/NodeConnect.js:16:9)
```

**Comment by Deivu** [comment]
Does this happen on everything, or select few voice connections

**Comment by LucasB25** [comment]
> Cela se produit-il sur tout ou sélectionne-t-il quelques connexions vocales ?

To what I saw a lot of vocal

**Comment by Deivu** [comment]
Does this happen when you normally play track or nope

**Comment by LucasB25** [comment]
these never produced at the time I was using the bot but in general I have users a little all the time

**Comment by Deivu** [comment]
Most likely it is a code issue on your side, seems like you are trying to resume players on boot?

Voice connection not established in 15 seconds just means you can't connect to that voice channel, so either you reconnect or drop it. If you can't still reconnect after multiple tries, then it is a code issue on your side, specially since you can connect normally.

**Comment by LucasB25** [comment]
https://github.com/appujet/lavamusic/blob/main/src/events/player/NodeConnect.ts

Several attempts have been made to see if this is code-driven but it’s a systemic concern
So I let you look at the code so that you can make your opinion about it and see if it comes from the code or shoukaku

**Comment by Deivu** [comment]
I'm pretty sure this isn't the library fault, I have my own implementation and it doesn't do that.

Again, the issue tracker is for bugs with the library, for general questions or help, or if you are unsure, better ask on our discord servers rather than here. You can find the links in README.md
