### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by makarasty** [shipgirlproject/Shoukaku#198]
I was unable to re-open your issue 

i use shoukaku 4.1.1, kazagumo 3.2.1
i get an error
```
RestError: Bad Request
    at Rest.fetch (C:\Users\MaKarastY\Desktop\LiveProjects\PutOffBeats\node_modules\shoukaku\dist\index.js:991:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Player.update (C:\Users\MaKarastY\Desktop\LiveProjects\PutOffBeats\node_modules\shoukaku\dist\index.js:711:5) {
  timestamp: 1725481234742,
  status: 400,
  error: 'Bad Request',
  trace: undefined,
  path: '/v4/sessions/ciywkvjegg914j8m/players/785107327413911592'
}
```
lavalink logs:
```
2024-09-04T23:20:33.711+03:00  INFO 19240 --- [Lavalink] [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:cat"
2024-09-04T23:20:34.708+03:00  INFO 19240 --- [Lavalink] [  XNIO-1 task-3] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: cat
2024-09-04T23:20:34.720+03:00  INFO 19240 --- [Lavalink] [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3Acat, client=0:0:0:0:0:0:0:1
2024-09-04T23:20:34.738+03:00  WARN 19240 --- [Lavalink] [  XNIO-1 task-3] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Could not read kotlinx.serialization.json.JsonImpl@56b39544: Unexpected JSON token at offset 330: Expected start of the object '{', but had '"' instead at path: $.track.userData<EOL>JSON input: .....1YmUAAAAAAAAAAA==","userData":"509734900182548489"},"replace.....]
2024-09-04T23:20:34.738+03:00  INFO 19240 --- [Lavalink] [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/ciywkvjegg914j8m/players/785107327413911592?noReplace=false, client=0:0:0:0:0:0:0:1, payload={"track":{"encoded":"QAAA2AMAQVRoZSBsYXN0IG9uZe2gve24gu2gve24giAjY2F0ICNmdW5ueWNhdHMgI3BldHMgI2Z1bm55cGV0cyAjc2hvcnRzAAlwZXQgbG92ZXIAAAAAAADqYAALOGllNWNzLVZBUWcAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj04aWU1Y3MtVkFRZwEAMGh0dHBzOi8vaS55dGltZy5jb20vdmkvOGllNWNzLVZBUWcvbXFkZWZhdWx0LmpwZwAAB3lvdXR1YmUAAAAAAAAAAA==","userData":"509734900182548489"},"replaceCurrent":false}
```
is it a lavalink or kazagumo problem?

**Comment by EvilG-MC** [comment]
Kazagumo uses a version of shoukaku that is not compatible with the current one.
Use a version that is compatible with kazagumo.

**Comment by makarasty** [comment]
The issue turned out to be with Kazagumo. Apologies for the incorrect issue report

![image](https://github.com/user-attachments/assets/4417b74d-dc02-4110-aa3b-8dfcd38ac852)
![image](https://github.com/user-attachments/assets/37c64429-0a19-4ae6-ae2f-1af2d4f6a908)
